spring:
  datasource:
    url: "jdbc:mysql://localhost:3310/schedule?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC"
    username: "root"
    password: "yunzhi"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.MySQL57Dialect"
    hibernate:
      ddl-auto: create-drop
    show-sql: true

#钉钉机器人推送
dingtalk:
  robot:
    url: "https://oapi.dingtalk.com/robot/send?access_token=8a5ca24b22b8078cd8bff2d69df2c5dc67764986961248301a625e9ffe900323"